package com.example.noteapp;

public interface KEY {
    String SP_BACKGROUND_SETTING = "BACKGROUND_SETTING";
    String BACKGROUND_COLOR = "BACKGROUND_COLOR";
    String APPBAR_COLOR = "APPBAR_COLOR";
    String ACTION= "ACTION";
    String ACTION_ADD= "ACTION_ADD";
    String ACTION_EDIT= "ACTION_EDIT";
    String NOTE_TITLE= "NOTE_TITLE";
    String NOTE_CONTENT= "NOTE_CONTENT";
    String NOTE_THEME_BG= "NOTE_THEME_BG";
    String NOTE_THEME_TT= "NOTE_THEME_TT";
    int RESULT_CODE_BACKGROUND_SETTING = 101;
    int RESULT_CODE_ADD_NOTE = 102;
    int RESULT_CODE_EDIT_NOTE = 103;
}
